// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mihoyo_fp.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DeviceInfo _$DeviceInfoFromJson(Map<String, dynamic> json) => DeviceInfo(
      romCapacity: json['romCapacity'] as String,
      deviceName: json['deviceName'] as String,
      productName: json['productName'] as String,
      romRemain: json['romRemain'] as String,
      hostname: json['hostname'] as String,
      screenSize: json['screenSize'] as String,
      isTablet: (json['isTablet'] as num).toInt(),
      aaid: json['aaid'] as String,
      model: json['model'] as String,
      brand: json['brand'] as String,
      hardware: json['hardware'] as String,
      deviceType: json['deviceType'] as String,
      devId: json['devId'] as String,
      serialNumber: json['serialNumber'] as String,
      sdCapacity: (json['sdCapacity'] as num).toInt(),
      buildTime: json['buildTime'] as String,
      buildUser: json['buildUser'] as String,
      simState: (json['simState'] as num).toInt(),
      ramRemain: json['ramRemain'] as String,
      appUpdateTimeDiff: (json['appUpdateTimeDiff'] as num).toInt(),
      deviceInfo: json['deviceInfo'] as String,
      buildType: json['buildType'] as String,
      sdkVersion: json['sdkVersion'] as String,
      uiMode: json['uiMode'] as String,
      isMockLocation: (json['isMockLocation'] as num).toInt(),
      cpuType: json['cpuType'] as String,
      isAirMode: (json['isAirMode'] as num).toInt(),
      ringMode: (json['ringMode'] as num).toInt(),
      chargeStatus: (json['chargeStatus'] as num).toInt(),
      manufacturer: json['manufacturer'] as String,
      emulatorStatus: (json['emulatorStatus'] as num).toInt(),
      appMemory: json['appMemory'] as String,
      osVersion: json['osVersion'] as String,
      vendor: json['vendor'] as String,
      accelerometer: json['accelerometer'] as String,
      sdRemain: (json['sdRemain'] as num).toInt(),
      buildTags: json['buildTags'] as String,
      packageName: json['packageName'] as String,
      networkType: json['networkType'] as String,
      oaid: json['oaid'] as String,
      debugStatus: (json['debugStatus'] as num).toInt(),
      ramCapacity: json['ramCapacity'] as String,
      magnetometer: json['magnetometer'] as String,
      display: json['display'] as String,
      appInstallTimeDiff: (json['appInstallTimeDiff'] as num).toInt(),
      packageVersion: json['packageVersion'] as String,
      gyroscope: json['gyroscope'] as String,
      batteryStatus: (json['batteryStatus'] as num).toInt(),
      hasKeyboard: (json['hasKeyboard'] as num).toInt(),
      board: json['board'] as String,
    );

Map<String, dynamic> _$DeviceInfoToJson(DeviceInfo instance) =>
    <String, dynamic>{
      'romCapacity': instance.romCapacity,
      'deviceName': instance.deviceName,
      'productName': instance.productName,
      'romRemain': instance.romRemain,
      'hostname': instance.hostname,
      'screenSize': instance.screenSize,
      'isTablet': instance.isTablet,
      'aaid': instance.aaid,
      'model': instance.model,
      'brand': instance.brand,
      'hardware': instance.hardware,
      'deviceType': instance.deviceType,
      'devId': instance.devId,
      'serialNumber': instance.serialNumber,
      'sdCapacity': instance.sdCapacity,
      'buildTime': instance.buildTime,
      'buildUser': instance.buildUser,
      'simState': instance.simState,
      'ramRemain': instance.ramRemain,
      'appUpdateTimeDiff': instance.appUpdateTimeDiff,
      'deviceInfo': instance.deviceInfo,
      'buildType': instance.buildType,
      'sdkVersion': instance.sdkVersion,
      'uiMode': instance.uiMode,
      'isMockLocation': instance.isMockLocation,
      'cpuType': instance.cpuType,
      'isAirMode': instance.isAirMode,
      'ringMode': instance.ringMode,
      'chargeStatus': instance.chargeStatus,
      'manufacturer': instance.manufacturer,
      'emulatorStatus': instance.emulatorStatus,
      'appMemory': instance.appMemory,
      'osVersion': instance.osVersion,
      'vendor': instance.vendor,
      'accelerometer': instance.accelerometer,
      'sdRemain': instance.sdRemain,
      'buildTags': instance.buildTags,
      'packageName': instance.packageName,
      'networkType': instance.networkType,
      'oaid': instance.oaid,
      'debugStatus': instance.debugStatus,
      'ramCapacity': instance.ramCapacity,
      'magnetometer': instance.magnetometer,
      'display': instance.display,
      'appInstallTimeDiff': instance.appInstallTimeDiff,
      'packageVersion': instance.packageVersion,
      'gyroscope': instance.gyroscope,
      'batteryStatus': instance.batteryStatus,
      'hasKeyboard': instance.hasKeyboard,
      'board': instance.board,
    };

FpBody _$FpBodyFromJson(Map<String, dynamic> json) => FpBody(
      device_id: json['device_id'] as String,
      seed_id: json['seed_id'] as String,
      seed_time: json['seed_time'] as String,
      platform: json['platform'] as String,
      device_fp: json['device_fp'] as String,
      app_name: json['app_name'] as String,
      ext_fields: json['ext_fields'] as String,
    );

Map<String, dynamic> _$FpBodyToJson(FpBody instance) => <String, dynamic>{
      'device_id': instance.device_id,
      'seed_id': instance.seed_id,
      'seed_time': instance.seed_time,
      'platform': instance.platform,
      'device_fp': instance.device_fp,
      'app_name': instance.app_name,
      'ext_fields': instance.ext_fields,
    };
